version: 2

models:
  - name: fct__all_dates_activity
    description: "A list of all distinct dates with activity indicators, including additional date attributes."
    columns:
      - name: calendar_date
        description: "The distinct date in the calendar, indicating each unique date."
      - name: day_of_week_name_short
        description: "The short name of the day of the week for the calendar date (e.g., Mon, Tue)."
      - name: week_start_date
        description: "The starting date of the week for the calendar date."
      - name: week_of_year
        description: "The week number of the year for the calendar date."
      - name: month_name_short
        description: "The short name of the month for the calendar date (e.g., Jan, Feb)."
      - name: quarter_start_date
        description: "The starting date of the quarter for the calendar date."
      - name: had_activity
        description: "Indicates if there was an activity on this date ('Yes' or 'No')."
        tests:
          - not_null:
              severity: warn

  - name: fct__daily_activity_scores
    description: |
      This model calculates the daily activity scores based on predefined weights for various activities. 
      It aggregates scores for all activities performed on a given day, providing a measure of daily productivity.
      It is using adjusted dates because the sleep time is usually around 10PM. So, days start from 10PM instead of midnight.
    columns:
      - name: adj_rhythm_date
        description: |
          The date of the activities, formatted as 'YYYY-MM-DD'. 
          This serves as the primary time dimension for tracking daily scores.
        tests:
          - not_null:
              severity: warn
      - name: adj_year_week_num
        description: |
          The date formatted as Year-Week Number (e.g., 2024-W1)
      - name: adj_weekday
        description: |
          The name of the day corresponding to the adj_rhythm_date (e.g., Monday, Tuesday).
      - name: adj_day_num
        description: |
          The numeric representation of the day within the week (e.g., 1 for Monday, 7 for Sunday).
      - name: adjusted_score
        description: |
          The aggregated activity score for all activities performed on a given date. 
          Higher scores indicate greater productivity or importance based on weighted activities.
        tests:
          - not_null:
              severity: warn

  - name: fct__finance_transactions
    description: "A fact table containing financial transaction data with enriched supplier details."
    columns:
      - name: transaction_date
        description: "The date of the transaction in 'YYYY-MM-DD' format."
      - name: supplier
        description: "The supplier involved in the transaction."
      - name: parent_supplier
        description: "The parent supplier for the transaction (from the supplier dimension)."
      - name: spend_category
        description: "The spend category for the supplier, assigned by the bank"
      - name: card_owner
        description: "The card owner associated with the transaction."
      - name: bank_name
        description: "The name of the bank associated with the transaction."
      - name: transaction_type
        description: "The type of transaction (e.g., purchase, payment)."
      - name: amount
        description: "The amount of the financial transaction."
      - name: memo
        description: "The memo or note associated with the transaction."

  - name: fct__gym_exercises
    description: "A fact table tracking gym exercises, including the exercise type, weight, and associated dates."
    columns:
      - name: gym_date
        description: "The date the gym exercise was performed."
      - name: gym_exercise_type
        description: "The type of exercise performed at the gym (e.g., squat, deadlift)."
      - name: gym_exercise_weight
        description: "The weight used for the exercise, if applicable."
      - name: gym_exercise_repetitions
        description: "The number of reps for the exercise, if applicable."
      - name: attribute_6
        description: "The attribute used to filter for gym-related data. Always equals 'gym'."

  - name: fct__other_rhythm_tracking
    description: |
      This model tracks various personal data over time, including mood, sleep score, body weight, and highlights or lowlights, providing insights into personal trends and behaviors for health and wellness monitoring.
    columns:
      - name: rhythm_date
        description: |
          The date when the personal data was recorded. This helps in tracking trends over time.
      - name: mood_score
        description: |
          The mood score recorded during the entry, measured on a numeric scale.
      - name: sleep_score
        description: |
          The sleep score recorded during the entry, measured on a numeric scale.
      - name: body_weight
        description: |
          The body weight recorded during the entry, measured in pounds (lbs).
      - name: highlight
        description: |
          A significant positive experience recorded during the entry, often reflecting accomplishments or key moments.
      - name: lowlight
        description: |
          A significant negative experience recorded during the entry, often reflecting challenges or setbacks.

  - name: fct__tennis_matches
    description: "Fact table for tennis matches, including match type (singles/doubles), score, and notes."
    columns:
      - name: match_id,
        description: "The unique identifier for the match."
      - name: gym_date
        description: "The date of the tennis match."
        tests:
          - not_null
      - name: match_type
        description: "The type of match (singles, doubles, or other tennis activity)."
      - name: score
        description: "The score of the tennis match."
      - name: teammate
        description: "The name of the tennis teammate"
      - name: opponents
        description: "The name of the tennis opponents"
      - name: notes
        description: "Any additional comments or notes about the match."
      - name: result
        description: "The result of the match (win or loss)."

  - name: fct__tennis_results
    description: |
      This model tracks the results of tennis matches, including whether the player was a teammate or an opponent. 
      It calculates the result ('Win' or 'Loss') based on the score for each player, and stores the match details 
      such as match_id, player_name, score, result, and whether the player was a teammate.
    columns:
      - name: match_id
        description: The unique identifier for each tennis match.
        tests:
          - not_null
      - name: player_name
        description: The name of the player (either a teammate or an opponent).
      - name: score
        description: The score of the match (e.g., '6-4').
      - name: result
        description: The result of the match for the player ('Win' or 'Loss').
      - name: is_teammate
        description: A boolean indicating whether the player is a teammate (TRUE) or an opponent (FALSE).