version: 2

models:
  - name: fct__all_dates_activity
    description: "A list of all distinct dates with activity indicators, including additional date attributes."
    columns:
      - name: calendar_date
        description: "The distinct date in the calendar, indicating each unique date."
      - name: day_of_week_name_short
        description: "The short name of the day of the week for the calendar date (e.g., Mon, Tue)."
      - name: week_start_date
        description: "The starting date of the week for the calendar date."
      - name: week_of_year
        description: "The week number of the year for the calendar date."
      - name: month_name_short
        description: "The short name of the month for the calendar date (e.g., Jan, Feb)."
      - name: quarter_start_date
        description: "The starting date of the quarter for the calendar date."
      - name: had_activity
        description: "Indicates if there was an activity on this date ('Yes' or 'No')."
        tests:
          - not_null:
              severity: warn

  - name: fct__tennis_matches
    description: "Fact table for tennis matches, including match type (singles/doubles), score, and notes."
    columns:
      - name: match_id,
        description: "The unique identifier for the match."
      - name: date
        description: "The date of the tennis match."
        tests:
          - not_null
      - name: match_type
        description: "The type of match (singles, doubles, or other tennis activity)."
      - name: score
        description: "The score of the tennis match."
      - name: notes
        description: "Any additional comments or notes about the match."
      - name: result
        description: "The result of the match (win or loss)."

  - name: fct__tennis_results
    description: |
      This model tracks the results of tennis matches, including whether the player was a teammate or an opponent. 
      It calculates the result ('Win' or 'Loss') based on the score for each player, and stores the match details 
      such as match_id, player_name, score, result, and whether the player was a teammate.
    columns:
      - name: match_id
        description: The unique identifier for each tennis match.
        tests:
          - not_null
      - name: player_name
        description: The name of the player (either a teammate or an opponent).
      - name: score
        description: The score of the match (e.g., '6-4').
      - name: result
        description: The result of the match for the player ('Win' or 'Loss').
      - name: is_teammate
        description: A boolean indicating whether the player is a teammate (TRUE) or an opponent (FALSE).
