version: 2

sources:
  - name: staging
    database: rhythm
     # For postgres:
      #database: production
    schema: public
      # loaded_at_field: record_loaded_at
    tables:
      - name: raw__finance
      - name: raw__rhythm
      - name: raw__gym
      - name: raw__professional
         # freshness:
           # error_after: {count: 6, period: hour}

models:
    - name: stg__finance  # Replace <model_name> with your model's name
      description: |
        This model processes raw finance data to create a structured table with cleaned and formatted fields such as transaction date, supplier, category, and more.
      columns:
        - name: transaction_date
          description: The transaction date formatted as an integer in YYYYMMDD format.
        - name: supplier
          description: The supplier associated with the transaction.
        - name: bank_spend_category
          description: The spend category of the transaction, assigned by the bank.
        - name: card_owner
          description: The owner of the card used for the transaction.
        - name: bank_name
          description: The name of the bank associated with the transaction.
        - name: transaction_type
          description: The type of transaction, e.g., credit or debit.
        - name: amount
          description: The transaction amount.
        - name: memo
          description: Additional notes or information about the transaction.

    - name: stg__food
      description: >
        Staging model that extracts food and restaurant information from the notes field 
        in the stg__rhythm table. Parses JSON-like strings to identify food consumed and 
        associated restaurant, if any.
      columns:
        - name: rhythm_date
          description: Date on which the food was consumed.
          tests:
            - not_null

        - name: food
          description: Name of the food item extracted from the notes field.

        - name: restaurant
          description: Name of the restaurant where the food was consumed, if provided.

    - name: stg__rhythm
      description: >
        15 minute interval time blocks to increase productivity 
        and minimize cognitive load of remembering what and when activities
        need to be completed
      columns:
        - name: activity_id
          description: This is the table's unique ID
          tests:
            - not_null:
                severity: warn
            - unique:
                severity: warn
          severity: warn
        - name: weekday
          description: Weekday of the date of activity
        - name: day_num 
          description: Weekday number of the date of activity
        - name: date 
          description: Date of activity
        - name: hour 
          description: The time of the activity
        - name: activity 
          description: Concatenation of activity from attribute_1 and attribute_2
        - name: attribute_1 
          description: Main category of activity
        - name: attribute_2
          description: Secondary category of activity
        - name: attribute_3
          description: Third category of activity
        - name: attribute_4
          description: Fourth category of activity
        - name: places
          description: location of the activity
        - name: people
          description: people involved in the activity
        - name: notes
          description: additional notes of activity
        - name: adj_weekday
          description: adjusted date of activity is 2 hours behind actual date of activity
        - name: adj_day_num
          description: 2 hours behind actual adj_day_num
        - name: adj_date
          description: 2 hours behind actual adj_date
        - name: adj_hour
          description: 2 hours behind actual adj_hour
    
    - name: stg__professional
      description: "A fact table that tracks professional status, including application phase, year applied, and associated details."
      columns:
        - name: application_id
          description: "Unique Identifier based on the appplication_link"
        - name: application_status
          description: "The current status of the professional in the application process (e.g., applied, interviewed, hired)."
        - name: application_phase
          description: "The phase number of the application process (e.g., Round 1, Round 2)."
        - name: application_phase_desc
          description: "The description of the phase of the application process (e.g., technical interview, behavioral interview)."
        - name: application_date
          description: "The date the application was submitted."
        - name: company_name
          description: "The name of the company where the application was submitted."
        - name: job_title
          description: "The title of the job applied for."
        - name: job_location
          description: "The location of the job opportunity."
        - name: application_link
          description: "A link to the job posting or relevant application details."

    - name: stg__gym
      description: >
        15 minute interval time blocks to increase productivity 
        and minimize cognitive load of remembering what and when activities
        need to be completed
      columns:
        - name: activity_id
          description: This is the table's unique ID
          tests:
            - not_null:
                severity: warn
        - name: Day
          description: Weekday of the date of activity
        - name: Day_num 
          description: Weekday number of the date of activity
        - name: Date 
          description: Date of activity
        - name: Hour 
          description: The time of the activity
        - name: Activity 
          description: Concatenation of activity from Attribute_1 and Attribute_2
        - name: Attribute_1 
          description: Main category of activity
        - name: Attribute_2
          description: Secondary category of activity
        - name: Attribute_3
          description: Third category of activity
        - name: Attribute_4
          description: Fourth category of activity
        - name: Attribute_5
          description: Fifth category of activity
        - name: Attribute_6
          description: Sixth category of activity
        - name: Notes
          description: additional notes of activity